repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      # Run the formatter first
      - id: ruff-format

      # Then run the linter (with autofix enabled)
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        files: \.(tsx|ts|js|jsx|json)$
