# Generated by Django 5.1.2 on 2024-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=1000)),
                ('other', models.CharField(max_length=1000)),
            ],
        ),
    ]
