name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
            version: "latest"
            args: "check"
            changed-files: "true"
      - uses: astral-sh/ruff-action@v3
        with:
            args: "format --check"
            changed-files: "true"
